app:
  instance-id: ${random.uuid}

spring:
  application:
    name: WalletService

  datasource:
    url: jdbc:postgresql://localhost:3307/wallet_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

logging:
  level:
    org.example.walletservice: DEBUG
    org.springframework.jdbc.core: DEBUG
